### ISSUE TITLE
Unable to view document files.

### ISSUE THREAD

**Issue by alfredmaliakal** [cyntler/react-doc-viewer#94]
![image](https://user-images.githubusercontent.com/14846350/204496579-8d1dd205-954c-4376-80ca-1d23787208f7.png)

**Comment by rturtu** [comment]
@cyntler the package also doesn't work with anything anymore to me. Is there any way to debug to see an error message?

**Comment by cyntler** [comment]
@rturtu anything anymore? since when? from which version?

**Comment by cyntler** [comment]
@alfredmaliakal looks like this problem: https://github.com/cyntler/react-doc-viewer/issues/16

**Comment by polkduran** [comment]
Working with 1.5.5 (need to update TS to upgrade version), I have the same issue with `doc` and `docx` but ok for `xls` and `xlsx` file from the same server.

**Comment by rturtu** [comment]
> @rturtu anything anymore? since when? from which version?
Since (at least) 1 month ago. We were using version 1.5.5, but even after upgrading to 1.10.1 it still doesn't work.

**Comment by cyntler** [comment]
@rturtu Ok, I understand. It does not work at all or for MS Office files only?

**Comment by rturtu** [comment]
@cyntler I just found the issue was on my end of the code. The package is working fine with both 1.5.5 and 1.10.1.

**Comment by polkduran** [comment]
> @polkduran As I wrote i.e. here: [#16 (comment)](https://github.com/cyntler/react-doc-viewer/issues/16#issuecomment-1180102717) - we use "Office Web Viewer" and all types of MS Office files are handling by this service. In the future I plan to implement some other way to render MS office files but at the moment I can't help probably.

thanks for the reply, yes I can see the iframe with the office viewer but just wanted to know if someone has any clue, maybe the way the url is encoded or something else, knowing that excel is working ok but doc and ppt are not working with the same office viewer.

@rturtu are you able to display doc/docx documents ?

**Comment by rturtu** [comment]
@polkduran nope, docx still doesn't work

**Comment by prem-pachouri-infopro** [comment]
Below code is working for me.
![image](https://user-images.githubusercontent.com/121174845/224718565-19dd03ad-b34b-40f9-81c1-6d646daa6607.png)

**Comment by alfredmaliakal** [comment]
@prem-pachouri-infopro  thank you for the update. It's working for me as well. I had issue with loading the internal files from db path. As a resolution, I create a temp blog and passed the blob as uri path. Thanks for the updates. @cyntler

**Comment by sime2408** [comment]
> 

So what is the solution, in the end, only the use of https links works?

**Comment by alfredmaliakal** [comment]
@sime2408  Please check this solution https://github.com/cyntler/react-doc-viewer/issues/94#issuecomment-1466163408. I have implemented something similar, and it's working fine.

**Comment by sime2408** [comment]
> @sime2408 Please check this solution [#94 (comment)](https://github.com/cyntler/react-doc-viewer/issues/94#issuecomment-1466163408). I have implemented something similar, and it's working fine. You can use the create object method and supply it to URI if you don't have the HTTP uri. In my case, I retrieved the file object using Ajax and converted it to URI. What it does is create a temporary object uri, which you may supply to the `const docs = {uri: "_temp_object uri_"}`

Not working since in dev mode I go to the localhost backend and this library whaps my request to https://view.officeapps.live.com/op/embed.aspx?src=... which of course can't reach my localhost

**Comment by SafaDeldoul** [comment]
did you please find a solution for this? I tried what you suggested but the .doc, .docx and .pptx are not working ..

**Comment by marciojuniors2** [comment]
After several hours of work I realized that we are being deceived by the property: pluginRenderers={DocViewerRenderers}
waiting for it to define the typings for the uri documents, but that doesn't happen! and the solution I found is to import the necessary types directly from DocViewerRenderers in this way:

`import PDFRendererfrom "./pdf";
`
and using fileType of documents:

```
            documents={[
              {
                uri: yourUrl
                fileType: PDFRenderer),
              },
            ]}
```

If you want to use more than one type, you can do it this way:

```
const supportedFileTypes = ["pdf", "png", "docx"];

  const getFileType = (fileName: string) => {
    const extension = fileName.split('.').pop()?.toLowerCase();
    return supportedFileTypes.includes(extension!) ? extension: 'default';
  };
```

and use in fileType:

```
            documents={[
              {
                uri: yourUrl
                fileType: getFileType(yourUrl),
              },
            ]}
```

version:  "@cyntler/react-doc-viewer": "1.14.0",

**Comment by Sakthisg43** [comment]
docx still doesn't work for me ,I face that issue..... @alfredmaliakal  I also implemeting same thing but its throw some error while try to opening a docx file .That file is on S3 Bucket and using the file key i try to presigned the url and using the url i try to open that but they showing error ...same implemention for pdf,xlsx also but these are working expect docx file ....

<img width="640" alt="Document error" src="https://github.com/cyntler/react-doc-viewer/assets/91771032/134dd4a0-5d26-4415-bb6b-d3556a46c17b">

**Comment by douglasc0leman** [comment]
I can't get any file to work: local or remote. I have confirmed that the blob data is populated correctly with the _blank code below. It downloads the expected file however when I pass that exact URI to the react-doc-viewer I get the generic An Error Occurred with nothing helpful in my console... Any ideas on why this is not working for me? 

`        let file = await fetch('https://graph.microsoft.com/v1.0/drives/' + driveId + '/items/' + itemId + '/content', 
            {method: 'GET', headers: {'Authorization': 'Bearer ' + graphAccessToken, 'Content-type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Access-Control-Allow-Origin': '*'}})
            .then(r => r.blob())
            .then(blobFile => {
                const urlToPreview = URL.createObjectURL(blobFile);
                console.log("urlToPreview", urlToPreview)
                window.open(urlToPreview, "_blank")?.focus()

                
                docArr.push({uri: urlToPreview})
                setDocs(docArr);
            })`
            
            
![image](https://github.com/cyntler/react-doc-viewer/assets/130193523/1826aaae-08d2-482f-a32d-73ade2bb2938)

**Comment by JamieShelley** [comment]
> I can't get any file to work: local or remote. I have confirmed that the blob data is populated correctly with the _blank code below. It downloads the expected file however when I pass that exact URI to the react-doc-viewer I get the generic An Error Occurred with nothing helpful in my console... Any ideas on why this is not working for me?
> 
> ![image](https://private-user-images.githubusercontent.com/130193523/335710769-ef210467-37f3-475c-bb37-fec04704d483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDM4NTYsIm5iZiI6MTczNTk0MzU1NiwicGF0aCI6Ii8xMzAxOTM1MjMvMzM1NzEwNzY5LWVmMjEwNDY3LTM3ZjMtNDc1Yy1iYjM3LWZlYzA0NzA0ZDQ4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QyMjMyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2Y0NTBlMmJkOTk0MTJmNzQ5OWY1OGI4MzdlZDVmNjVhMDU5YzZkNDkzYWE5NGE5NmRlZGYxNGMyMGY1YjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cuZUFT6stcBczedrsYZd2MzugbsLVoiFXkwAFaSxBRg)
> 
> The console spits out blob:http://localhost:8080/dd1f8e9b-8d92-4f21-bb67-e34410160e12 for urlToPreview. From http:// on it's a hyperlink. If I click that hyperlink it goes to a White Screen error for my spring boot backend. If I copy the whole thing (including the preceeding 'blob:') and paste it in my browser and hit enter, it downloads the .xlsx file. Is what I am passing to react-doc-viewer incorrect?
> 
> ![image](https://private-user-images.githubusercontent.com/130193523/335708350-1826aaae-08d2-482f-a32d-73ade2bb2938.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDM4NTYsIm5iZiI6MTczNTk0MzU1NiwicGF0aCI6Ii8xMzAxOTM1MjMvMzM1NzA4MzUwLTE4MjZhYWFlLTA4ZDItNDgyZi1hMzJkLTczYWRlMmJiMjkzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QyMjMyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGMwMmRhZDRkMGE3MGRiMDE3M2NiMzNmZDExMmI0YTk0OWQ0YzU1MWJkYWZjMTczNWYwMDM4ZDNiMzZmZjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ukHNS-L2hV1kr37FPHMyow0F2qrATo0nq1KO1dEbPl0) tthis is my whitescreen error: ![image](https://private-user-images.githubusercontent.com/130193523/335709834-4a4f4019-fa59-4618-945d-49bc6b22891c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDM4NTYsIm5iZiI6MTczNTk0MzU1NiwicGF0aCI6Ii8xMzAxOTM1MjMvMzM1NzA5ODM0LTRhNGY0MDE5LWZhNTktNDYxOC05NDVkLTQ5YmM2YjIyODkxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QyMjMyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2YzNTU1N2IwMDA3ZTNjMWI5ZmM5MGM4ZTY4NTFiZjk2YjkwMjJiNzNjMDNkZWQxMmFlMjQwZGU2OGI0NzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q__WRvzgDw1fawlbOZoNRd4f-uLBYWQILUgESuXuHRE)

I have the same issue here.. nothing to add in terms of fixes yet at least, sorry.
